# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
    echo "deb https://dl.bintray.com/loadimpact/deb stable main" | sudo tee -a /etc/apt/sources.list
    sudo apt-get update
    sudo apt-get install k6
  displayName: Install k6 tool

- script: |
    k6 version
  displayName: Check if k6 is installed

- script: |
    k6 login cloud -t 10bb84a64582068564b38cc47db705db6a8439a2ca6506fd4b71de1641d3d1b7
    k6 cloud --quiet loadtests/cloud.js
  displayName: Run k6 cloud load test within Azure Pipelines  